// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebFilms.DataAccess;

namespace DataAccess.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.DataAccess.Entity.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("FilmId");

                    b.Property<Guid>("UserId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("WebFilms.DataAccess.Entity.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160);

                    b.Property<Guid>("FilmId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WebFilms.DataAccess.Entity.Film", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("GenreId");

                    b.Property<string>("ImageXPath")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.Property<string>("YoutubeId");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Films");

                    b.HasData(
                        new { Id = new Guid("101456bf-f3d9-41d2-83c3-83c08e82e9ce"), Description = "The surviving Resistance faces the First Order once more in the final chapter of the Skywalker saga.", GenreId = 3, ImageXPath = "https://m.media-amazon.com/images/M/MV5BZWU1NDI3YjEtZTlmMy00Y2FmLWI1ZDYtMjYwNDUxYTdlODllXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_SY1000_CR0,0,675,1000_AL_.jpg", Name = "Star Wars", YoutubeId = "Q1qZ6oLV3hg" },
                        new { Id = new Guid("a4e1be53-3dc8-4dcd-8e88-90afd08955e4"), Description = "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.", GenreId = 1, ImageXPath = "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_.jpg", Name = "The Green Mile", YoutubeId = "CmxArNBJHFQ" },
                        new { Id = new Guid("a9c23655-6f85-4684-b172-c7c48ff5958e"), Description = "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.", GenreId = 1, ImageXPath = "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg", Name = "The Shawshank Redemption", YoutubeId = "6hB3S9bIaco" },
                        new { Id = new Guid("aa827ecf-d24c-4080-b3a2-478c089cd9ae"), Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", GenreId = 1, ImageXPath = "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,686,1000_AL_.jpg", Name = "Pulp Fiction", YoutubeId = "Y6YBKdmOlM8" },
                        new { Id = new Guid("f99d646d-2054-49a3-a109-84f9d43ea257"), Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", GenreId = 1, ImageXPath = "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,704,1000_AL_.jpg", Name = "The GodFather", YoutubeId = "sY1S34973zA" },
                        new { Id = new Guid("3aa7fc8f-3398-440a-9f6a-78f752db52fc"), Description = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.", GenreId = 3, ImageXPath = "https://m.media-amazon.com/images/M/MV5BNGE5MzIyNTAtNWFlMC00NDA2LWJiMjItMjc4Yjg1OWM5NzhhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,684,1000_AL_.jpg", Name = "The Lord of the Rings", YoutubeId = "r5X-hFf6Bwo" }
                    );
                });

            modelBuilder.Entity("WebFilms.DataAccess.Entity.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new { GenreId = 1, Name = "Action" },
                        new { GenreId = 2, Name = "Drama" },
                        new { GenreId = 3, Name = "Comedy" },
                        new { GenreId = 4, Name = "Adventure" },
                        new { GenreId = 5, Name = "Documentaly" },
                        new { GenreId = 6, Name = "Horror" },
                        new { GenreId = 7, Name = "Romance" }
                    );
                });

            modelBuilder.Entity("WebFilms.DataAccess.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = new Guid("2c6270df-c885-4b52-b58d-ec44bf6b6e87"), Email = "zyglin@mail.ru", FullName = "Zyglin Artem Pavlovich", PasswordHash = "15000|NHH5cx2La/tUttq2|LzmB18TbKeGKoRFcCtaZvWh+0+SZA8SnLefqRqKoGc8=", PhoneNumber = "+375291641585" }
                    );
                });

            modelBuilder.Entity("DataAccess.DataAccess.Entity.Rating", b =>
                {
                    b.HasOne("WebFilms.DataAccess.Entity.Film", "Film")
                        .WithMany("Ratings")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebFilms.DataAccess.Entity.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebFilms.DataAccess.Entity.Comment", b =>
                {
                    b.HasOne("WebFilms.DataAccess.Entity.Film", "Film")
                        .WithMany("Comments")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebFilms.DataAccess.Entity.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebFilms.DataAccess.Entity.Film", b =>
                {
                    b.HasOne("WebFilms.DataAccess.Entity.Genre", "Genre")
                        .WithMany("Films")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
